 

public static class People
{
    public static string[] peopleNames = {
            "Focker" ,"Frogger"
     ,"Blimpie"
     ,"Foxy Mama"
     ,"Robin"
     ,"Pixie"
     ,"Chef"
     ,"Bub"
     ,"Cupcake"
     ,"Lover"
     ,"Terminator"
     ,"Rocketfuel"
     ,"First Mate"
     ,"Elf"
     ,"Bubble Butt"
     ,"Birdy"
     ,"Mad Max"
     ,"Wilma"
     ,"French Fry"
     ,"Duckling"
     ,"Mustache"
     ,"Friendo"
     ,"Cruella"
     ,"Muscles"
     ,"Cloud"
     ,"Bessie"
     ,"Mini Mini"
     ,"Blondie"
     ,"Candycane"
     ,"Music Man"
     ,"Beauty"
     ,"Guapo"
     ,"Sunny"
     ,"Belle"
     ,"Dropout"
     ,"Mini Me"
     ,"Double Double"
     ,"Dragon"
     ,"Janitor"
     ,"Fox"
     ,"Thunder Thighs"
     ,"Joker"
     ,"Boo Boo"
     ,"Jackrabbit"
     ,"Dottie"
     ,"Double Bubble"
     ,"Daria"
     ,"Dumbledore"
     ,"Baby Carrot"
     ,"Buttercup"
     ,"Chico"
     ,"Diesel"
     ,"Goon"
     ,"Bean"
     ,"Baldie"
     ,"Honey Pie"
     ,"Snickerdoodle"
     ,"Herp Derp"
     ,"Righty"
     ,"Amazon"
     ,"Queenie"
     ,"Bumblebee"
     ,"Bug"
     ,"Doc"
     ,"Gingersnap"
     ,"T-Dawg"
     ,"Smoochie"
     ,"Loser"
     ,"Cutie Pie"
     ,"Harry Potter"
     ,"Hammer"
     ,"Cricket"
     ,"Tiny"
     ,"Pookie"
     ,"Tata"
     ,"Maestro"
     ,"Amigo"
     ,"Dirty Harry"
     ,"Lil Girl"
     ,"Admiral"
     ,"Cookie Dough"
     ,"Kirby"
     ,"Honey Locks"
     ,"Twinkly"
     ,"Halfmast"
     ,"Toots"
     ,"Winnie"
     ,"Cheeky"
     ,"Tootsie"
     ,"Psycho"
     ,"Superman"
     ,"Punk"
     ,"Ladybug"
     ,"Rambo"
     ,"Cuddles"
     ,"Miss Piggy"
     ,"Grumpy"
     ,"Dimples"
     ,"Dud"
     ,"Pearl"
     ,"Hulk"
     ,"Cannoli"
     ,"Sassafras"
     ,"Captain Crunch"
     ,"Cinnamon"
     ,"Scout"
     ,"Monkey"
     ,"Snoopy"
     ,"Dearey"
     ,"Smarty"
     ,"4-Wheel"
     ,"Happy"
     ,"Boomer"
     ,"Short Shorts"
     ,"Squirt"
     ,"Snickers"
     ,"Gator"
     ,"Loosetooth"
     ,"Rubber"
     ,"Bandit"
     ,"Biscuit"
     ,"Braveheart"
     ,"Hubby"
     ,"Fifi"
     ,"Buster"
     ,"String Bean"
     ,"Conductor"
     ,"Hulk"
     ,"Baby Bird"
     ,"Butter"
     ,"Mini Skirt"
     ,"Cold Front"
     ,"Dracula"
     ,"Cindy Lou Who"
     ,"Buffalo"
     ,"Bumpkin"
     ,"Ami"
     ,"Ms. Congeniality"
     ,"Sugar"
     ,"Ace"
     ,"Cheeto"
     ,"Pickle"
     ,"Bud"
     ,"Dot"
     ,"Little Bear"
     ,"Wifey"
     ,"Foxy"
     ,"Buddy"
     ,"Drake"
     ,"Dinosaur"
     ,"Dorito"
     ,"Goose"
     ,"PB&J"
     ,"Teeny"
     ,"Kitten"
     ,"Goonie"
     ,"Sassy"
     ,"Tater Tot"
     ,"Genius"
     ,"Sunshine"
     ,"Pintsize"
     ,"Skunk"
     ,"Tyke"
     ,"Hawk"
     ,"Chance"
     ,"Sweet Tea"
     ,"Hot Sauce"
     ,"Muffin"
     ,"Schnookums"
     ,"Chewbacca"
     ,"MomBod"
     ,"Weirdo"
     ,"Itchy"
     ,"Brown Sugar"
     ,"Ginger"
     ,"Chiquita"
     ,"Champ"
     ,"Baby"
     ,"Goblin"
     ,"Chain"
     ,"Tarzan"
     ,"Red Velvet"
     ,"Sweety"
     ,"Freckles"
     ,"Eagle"
     ,"Anvil"
     ,"Lefty"
     ,"Donut"
     ,"Swiss Miss"
     ,"Peppermint"
     ,"Big Guy"
     ,"Mr. Clean"
     ,"Big Nasty"
     ,"Boo"
     ,"Lion"
     ,"Twizzler"
     ,"Knucklebutt"
     ,"Carrot"
     ,"Cutie"
     ,"Toodles"
     ,"Turtle"
     ,"Angel"
     ,"Marshmallow"
     ,"Heisenberg"
     ,"Figgy"
     ,"Smiley"
     ,"Apple"
     ,"Ghoulie"
     ,"Slim"
     ,"Doll"
     ,"Mountain"
     ,"Cuddle Pig"
     ,"Pig"
     ,"Creep"
     ,"Marge"
     ,"Chuckles"
     ,"Freak"
     ,"Thumper"
     ,"Guy"
     ,"Turkey"
     ,"Midge"
     ,"Butterfinger"
     ,"Rumplestiltskin"
     ,"Beef"
     ,"Ducky"
     ,"Honeybun"
     ,"Baby Boo"
     ,"Pop Tart"
     ,"Shuttershy"
     ,"Smirk"
     ,"Stitch"
     ,"Ash"
     ,"Baby Maker"
     ,"Babs"
     ,"Speedy"
     ,"Gumdrop"
     ,"Spicy"
     ,"Dummy"
     ,"Inchworm"
     ,"Goldilocks"
     ,"Hermione"
     ,"Manatee"
     ,"Autumn"
     ,"Betty Boop"
     ,"Tomcat"
     ,"General"
     ,"Cold Brew"
     ,"Senorita"
     ,"Fun Dip"
     ,"Pinata"
     ,"Boo Bug"
     ,"Chubs"
     ,"Master"
     ,"Taco"
     ,"Starbuck"
     ,"Headlights"
     ,"Pinkie"
     ,"Dunce"
     ,"Halfling"
     ,"Skinny Minny"
     ,"Belch"
     ,"Catwoman"
     ,"Big Mac"
     ,"Chickie"
     ,"Foxy Lady"
     ,"Cowboy"
     ,"Huggie"
     ,"Pretty Lady"
     ,"Sweetums"
     ,"Pixie Stick"
     ,"Pickles"
     ,"Dulce"
     ,"Creedence"
     ,"Mimi"
     ,"Biffle"
     ,"Rapunzel"
     ,"Bacon"
     ,"Skinny Jeans"
     ,"Bossy"
     ,"Raindrop"
     ,"Spud"
     ,"Bambino"
     ,"C-Dawg"
     ,"Dum Dum"
     ,"Munchkin"
     ,"Fun Size"
     ,"Lady"
     ,"Butterbuns"
     ,"Princess"
     ,"Bootsie"
     ,"Papito"
     ,"Red"
     ,"Fattykins"
     ,"LaLa"
     ,"Bebe"
     ,"Snuggles"
     ,"Bubblegum"
     ,"Tank"
     ,"Lulu"
     ,"Captain"
     ,"Dirt"
     ,"Coach"
     ,"Kitty"
     ,"Matey"
     ,"Chica"
     ,"Cheddar"
     ,"Chicken Wing"
     ,"Shorty"
     ,"Lovey"
     ,"Darling"
     ,"Daffodil"
     ,"Gummy Pop"
     ,"Gams"
     ,"Slick"
     ,"Cotton"
     ,"Oompa Loompa"
     ,"Homer"
     ,"Dino"
     ,"Fly"
     ,"Sourdough"
     ,"Chili"
     ,"Mouse"
     ,"Tater"
     ,"Buzz"
     ,"Moose"
     ,"Twix"
     ,"Amore"
     ,"Snow White"
     ,"Popeye"
     ,"Senior"
     ,"Nerd"
     ,"Ringo"
     ,"Juicy"
     ,"Button"
     ,"Redbull"
     ,"Buds"
     ,"Smudge"
     ,"Backbone"
     ,"Babe"
     ,"Rufio"
     ,"Salt"
     ,"Prego"
     ,"Frau Frau"
     ,"Peep"
     ,"Fellow"
     ,"Bello"
     ,"Rockette"
     ,"Dear"
     ,"Rabbit"
     ,"Pyscho"
     ,"Diet Coke"
     ,"Frodo"
     ,"Mistress"
     ,"Cello"
     ,"Amor"
     ,"Tickles"
     ,"Flower"
     ,"Apple Jack"
     ,"Dreamey"
     ,"Candy"
     ,"Donuts"
     ,"Sleeping Beauty"
     ,"Dots"
     ,"Sweet 'n Sour"
     ,"Beanpole"
     ,"Bubbles"
     ,"Grease"
     ,"Doofus"
     ,"Amour"
     ,"Raisin"
     ,"Lil Mama"
     ,"Silly Gilly"
     ,"Einstein"
     ,"Fury"
     ,"Kid"
     ,"Cheerio"
     ,"Lobster"
     ,"Rosie"
     ,"Rosebud"
     ,"Chump"
     ,"Tough Guy"
     ,"Gordo"
     ,"Frauline"
     ,"Cheesestick"
     ,"Scarlet"
     ,"Bambi"
     ,"Gummi Bear"
     ,"Boomhauer"
     ,"Flyby"
     ,"Junior"
     ,"Pork Chop"
     ,"Buckeye"
     ,"Romeo"
     ,"Piglet"
     ,"Highbeam"
     ,"Cumulus"
     ,"Frankfurter"
     ,"Braniac"
     ,"Coke Zero"
     ,"Silly Sally"
     ,"Pecan"
     ,"Amorcita"
     ,"Doobie"
     ,"Bellbottoms"
     ,"Bubba"
     ,"Beautiful"
     ,"Con"
     ,"Cottonball"
     ,"Numbers"
     ,"Peppa Pig"
     ,"Dragonfly"
     ,"Doctor"
     ,"Bunny Rabbit"
     ,"Twiggy"
     ,"Green Giant"
     ,"Colonel"
     ,"Ticklebutt"
     ,"Gizmo"
     ,"Big Bird"
     ,"Barbie"
     ,"Cat"
     ,"Golden Graham"
     ,"Amethyst"
     ,"Fatty"
     ,"Butternut"
     ,"DJ"
     ,"Lovely"
     ,"Filly Fally"
     ,"Rainbow"
     ,"Shrinkwrap"
     ,"Beast"
     ,"Shnookie"
     ,"Sherlock"
     ,"Kit-Kat"
     ,"Twig"
     ,"Jet"
     ,"Bridge"
     ,"Ice Queen"
     ,"Skipper"
     ,"Luna"
     ,"Twinkie"
     ,"Cookie"
     ,"Dearest"
     ,"Queen Bee"
     ,"Dingo"
     ,"Pebbles"
     ,"Crumbles"
     ,"Cheese"
     ,"Pansy"
     ,"Fido"
     ,"Piggy"
     ,"Dimpling"
     ,"Chief"
     ,"Chip"
     ,"Half Pint"
     ,"Cherry"
     ,"Red Hot"
     ,"Buck"
     ,"Bruiser"
     ,"Sport"
     ,"Beetle"
     ,"Bunny"
     ,"Brutus"
     ,"Hot Pepper"
     ,"Chicken Legs"
     ,"Stud"
     ,"Boo Bear"
     ,"Thor"
     ,"Baby Cakes"
     ,"Azkaban"
     ,"Dork"
     ,"Weiner"
     ,"Giggles"
     ,"Fiesta"
     ,"Dolly"
     ,"Chum"
     ,"Snake"
     ,"Dilly Dally"
     ,"Amiga"
    };

    public static string GetRandomName() {
        string name= peopleNames[UnityEngine.Random.Range(0,peopleNames.Length)];
        return name;
    }

    public static string GetName(int index)
    {
        string name = peopleNames[index % peopleNames.Length];
        return name;
    }

}





